export const KNOWN_UPI_APPS: Record<string, { name: string; brand: string }> = {
  'com.phonepe.app': { name: 'PhonePe', brand: '#5F259F' },
  'com.google.android.apps.nbu.paisa.user': { name: 'Google Pay', brand: '#1A73E8' },
  'net.one97.paytm': { name: 'Paytm', brand: '#00BAF2' },
  'in.amazon.mShop.android.shopping': { name: 'Amazon Pay', brand: '#FF9900' },
  'com.whatsapp': { name: 'WhatsApp Pay', brand: '#25D366' },
  'com.tatadigital.tcp': { name: 'Tata Neu', brand: '#5A2D82' },
  'com.bajajfinservmarkets.app': { name: 'Bajaj Finserv', brand: '#0B4DA2' },
  'com.dreamplug.androidapp': { name: 'CRED', brand: '#141414' },
  'com.naviapp': { name: 'Navi', brand: '#2F6BFF' },
  'com.nextbillion.groww': { name: 'Groww Pay', brand: '#00D09C' },
  'com.mobikwik_new': { name: 'MobiKwik', brand: '#00509D' },
  'in.slice.android': { name: 'Slice', brand: '#6A4DFF' },
  'money.super.payments': { name: 'Super.money', brand: '#00C853' },
  'club.popclub.android': { name: 'PopClub', brand: '#FF3D71' },
  'in.org.npci.upiapp': { name: 'BHIM', brand: '#F7941D' },
  'com.csam.icici.bank.imobile': { name: 'iMobile Pay', brand: '#AE275F' },
  'com.hdfcbank.payzapp': { name: 'PayZapp', brand: '#004C8F' },
};
